# Generated by Django 5.1.7 on 2025-11-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='progress',
        ),
    ]
